


export const metadata = {
    title: 'progect-about',
    description: 'Generated by create next app progect Doctor pation',
  }
  

import * as React from 'react';
// import {AiOutlineLeftCircle,AiOutlineFrown ,AiFillEnvironment,AiFillPhone} from "react-icons/ai"
// import {mdMdOutlineSick} from "react-icons/"
import HeaderD, { HeaderO } from "../header/page";
import Footer from '../footer/page';
import Image from 'next/image';
function Appoint() {
return (
<div className='relative h-[100%] w-[100%]'>
 

<div className='w-[100%]   text-center '>
        
<div className="flex flex-warb h-[80px] mb-8">
<div className="w-[60%] h-[50px]  bg-[#1e272e] text-white absolute top-0">
<HeaderD />
</div>
<div className="w-[40%] h-[50px]  bg-[#1e272e] absolute top-0 right-0">
<HeaderO />
</div>
</div>

<div className="w-[100%] h-[200px] bg-[#1e272e] relative flex">
<div className="w-[250px] relative mr-2">
<Image  className='absolute bottom-0 h-[250px] w-[220px] ml-4' src="/443.png" alt="img" width={200} height={200} />
</div>
<div className="text-start ml-6">
<p className='text-white font-medium mb-2'>AppoINTMENT</p>
<h1 className='text-white font-bold'>Make an appointment Today</h1>
<p className='text-[15px]  text-[#ffffff99] mb-2'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Non inventore perferendis necessitatibus debitis optio, </p>
<button className='bg-[white] font-bold  w-[110px] mt-2'>Learn more</button>
</div>

</div>
</div>
<div className="mt-12 ml-2"> 
<p className='text-[#6195ff] font-medium'>TESTIMONIAL</p>
<h1 className='text-[#1e272e] mt-2 font-bold w-[170px]' >What is Our patient Says</h1>
</div>
<div className="flex mt-12 justify-center flex-wrap">

<div className="w-[250px] mt-2 m-2 shadow-md shadow-black p-2">
<p className='text-[rgba(0,0,0,0.67)]  mb-10 text-[15px]'>Lorem ipsum dolor sit amet,
consectetur adipisicing elit.
Quo blanditiis cupiditate facilis placeat,
</p>
<div className="flex">
<Image className='w-[50px] h-[50px] rounded-full' src="/449.jpg" alt="image" width={50} height={50} />

<div className="block ml-2">
<h1 className='text-[#6195ff] font-medium'>Sayed Mohamed</h1>
<p>cairo</p>
</div>  
</div>

</div>

<div className="w-[250px] mt-2 m-2 shadow-md shadow-black p-2">
<p className='text-[#000000ab] mb-10 text-[15px]'>Lorem ipsum dolor sit amet,
consectetur adipisicing elit.
Quo blanditiis cupiditate facilis placeat,
</p>
<div className="flex">
<Image className='w-[50px] h-[50px] rounded-full' src="/449.jpg" alt="image" width={50} height={50} />

<div className="block ml-2">
<h1 className='text-[#6195ff] font-medium'>Sayed Mohamed</h1>
<p>cairo</p>
</div>  
</div>

</div>

<div className="w-[250px] mt-2 m-2 shadow-md shadow-black p-2">
<p className='text-[#000000ab] mb-10 text-[15px]'>Lorem ipsum dolor sit amet,
consectetur adipisicing elit.
Quo blanditiis cupiditate facilis placeat,
</p>
<div className="flex">
<Image className='w-[50px] h-[50px] rounded-full' src="/449.jpg" alt="image" width={50} height={50} />

<div className="block ml-2">
<h1 className='text-[#6195ff] font-medium'>Sayed Mohamed</h1>
<p>cairo</p>
</div>  
</div>

</div>

<div className="w-[250px] mt-2 m-2 shadow-md shadow-black p-2">
<p className='text-[#000000ab] mb-10 text-[15px]'>Lorem ipsum dolor sit amet,
consectetur adipisicing elit.
Quo blanditiis cupiditate facilis placeat,
</p>
<div className="flex">
<Image className='w-[50px] h-[50px] rounded-full' src="/449.jpg" alt="image" width={50} height={50} />

<div className="block ml-2">
<h1 className='text-[#6195ff] font-medium'>Sayed Mohamed</h1>
<p>cairo</p>
</div>  
</div>

</div>
</div>
<Footer/>
</div>
);
};

export default Appoint;