// @flow strict

export const metadata = {
  title: "progect-contact",
  description: "Generated by create next app progect Doctor pation",
};

import * as React from "react";
// import {AiOutlineLeftCircle,AiOutlineFrown ,AiFillEnvironment,AiFillPhone, AiOutlineArrowRight} from "react-icons/ai"
// import {mdMdOutlineSick} from "react-icons/"
import HeaderD, { HeaderO } from "../header/page";
import Footer from "../footer/page";
// import QRCode from 'react-qr-code';

function Contact() {
  return (
    <>
      <div className="flex  flex-warb ">
        <div className="w-[60%] bg-[#1e272e] text-white h-[50px] absolute top-0 ">
          <HeaderD />
        </div>
        <div className="w-[40%] h-[50px] bg-[#1e272e]  absolute top-0 right-0">
          <HeaderO />
        </div>
      </div>

      <div className="w-[100%] h-[100vh] sm:h-[80vh] md:h-[90vh] bg-[#1e272e] text-center  ">
        <div className="">
          <h1 className="text-[#6195ff] font-bold relative top-20">
            Contact us
          </h1>
          <div className="mt-28">
            <h2 className="text-white font-bold text-[22px]">
              Always Connect With us
            </h2>
            <input
              className="pl-2 focus:border-none w-[60%] h-[40px] m-2"
              type="email"
              name="email"
              placeholder="Enter Email"
            />
            <input
              className="pl-2 focus:border-none w-[60%] h-[40px]"
              type="text"
              name=""
              placeholder="Subject"
            />
            <input
              className="pl-2 focus:border-[none] pb-10 w-[60%] m-2 h-[70px]"
              type="text"
              name=""
              placeholder="Subject"
            />
            <div className="">
              <button className="bg-[#6195ff] text-white font-bold w-[150px] rounded">
                Supmit
              </button>
            </div>
          </div>
        </div>
        {/* <div className="absolute top-0 z-10 ">
    <QRCode value='https://bortfoli-sayed.vercel.app/' />
    </div> */}
      </div>
      <Footer />
    </>
  );
}

export default Contact;
