import './globals.css'
import { Inter } from 'next/font/google'
import { Montserrat } from 'next/font/google'
const bodyfont=Montserrat({
  subsets:['latin'],
  weight:["400" ,"700" ,"900"]
})


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyfont.className}>
  <main>        {children}</main>
  
        </body>
    </html>
  )
}
