
export const metadata = {
    title: 'Progect-Home',
    description: 'Generated by create next app progect Doctor pation',
  }
  
import HeaderD, { HeaderO } from '../app/header/page';
import Hom from '.././app/hom/page';
import Show from '../app/show/page';
import Footer from '../app/footer/page';
function HomeD() {
return (
<div className='w-[100%] h-auto relative'>

<div className="flex flex-warb h-[80px] ">
<div className="w-[65%] sm:w-[60%] h-[560px] bg-white absolute top-0">
<HeaderD />

</div>
<div className="w-[35%] sm:w-[40%] h-[560px] bg-[#1e272e] absolute top-0 right-0">
<HeaderO />

</div>

</div>
<div className="h-[450px]">
<Show/>

</div>
<div className="">
<Hom />

</div>
<Footer/>
</div>
);
};

export default HomeD;