// @flow strict


export const metadata = {
  title: 'progect-service',
  description: 'Generated by create next app progect Doctor pation',
}

import * as React from 'react';
import HeaderD, { HeaderO } from '../header/page';
import Footer from '../footer/page';
import Image from 'next/image';
function Services() {
    return (
      <>
        
<div className="flex  flex-warb mb-20 ">
<div className="w-[60%] bg-[#1e272e] text-white h-[50px] absolute top-0">
<HeaderD />

</div>
<div className="w-[40%] h-[50px] bg-[#1e272e]  absolute top-0 right-0">
<HeaderO />

</div>

</div>

        <div className='w-[100%]  relative text-center bg-white'>
        <h1 className='font-medium bg-[#6195ff] text-white '>Our Services</h1>
      <h2 className='font-bold text-[25px] mt-4'>Services We Provide</h2>
      <div className="flex flex-wrap mt-10 justify-around ">
      <div className="text-center m-2 w-[200px]">
        <Image src="/teath2.png" width={100} height={100} className='flex justify-center m-auto text-[60px] text-[#6195ff] ' alt='Image'>
        </Image>
<h1 className='font-bold text-lg'>fluoride Treatment</h1>
<p className='text-center text-[#00000080] pl-2'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, </p>
        </div>
        <div className="text-center m-2 w-[200px]">
        <Image src="/teath5.png" width={100} height={100} className='flex justify-center m-auto text-[60px] text-[#6195ff] ' alt='Image'>
        </Image>
        <h1 className='font-bold text-lg'>Cavity Filling</h1>
<p className='text-center text-[#00000080] pl-2'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, </p>
        </div>
        <div className="text-center m-2 w-[200px]">
        <Image src="/teath3.png" width={100} height={100} className='flex justify-center m-auto text-[60px] text-[#6195ff] ' alt='Image'>
        </Image>
        <h1 className='font-bold text-lg'>Teath Whitening</h1>
<p className='text-center text-[#00000080] pl-2'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, </p>
        </div>
      </div>
      <div className="flex justify-start flex-wrap mt-10 w-screen">
        <div className="w-[200px]  sm:w-[300px]  lg:w-[400px]">
          <Image className='w-[70%] h-[300px] m-auto' src="/665.jpg" alt="image" width={300} height={300} />
        </div>
        <div className="w-[270px] sm:w-[340px] lg:w-[400px]">
          <div className="w-[70%] text-start m-auto">

          <h1 className='font-bold text-lg'>Exceptional Dental Care, on Your Terms</h1>
          <p className='text-[15px]  text-[#00000080] font-medium'>Lorem ipsum dolor, sit amet consectetur adipisicing elit.
             Incidunt, doloremque ea culpa at repellat dolor tenetur enim veritatis 
             explicabo a error dolorum
              sit commodi nobis, 
            dignissimos beatae? Nesciunt, excepturi inventore.
            </p>
            <button className='font-medium text-white bg-[#6195ff] w-[110px]'>Learn more</button>
          </div>
        </div>
      </div>
        </div>
        <Footer/>
      </>
    );
};

export default Services;