// @flow strict


export const metadata = {
    title: 'Progect-Review',
    description: 'Generated by create next app progect Doctor pation',
  }
  


import * as React from 'react';
// import {AiOutlineLeftCircle,AiOutlineFrown ,AiFillEnvironment,AiFillPhone, AiOutlineArrowRight} from "react-icons/ai"
// import {mdMdOutlineSick} from "react-icons/"
import HeaderD, { HeaderO } from '../header/page';
import Footer from '../footer/page';
import Image from 'next/image';

function Blog() {
return (
<>
      
<div className="flex  flex-warb mb-20">
<div className="w-[60%] bg-[#1e272e] text-white h-[50px] absolute top-0">
<HeaderD />

</div>
<div className="w-[40%] h-[50px] bg-[#1e272e]  absolute top-0 right-0">
<HeaderO />

</div>

</div>

<div className='w-[100%]   text-center mt-12 mb-[50px] '>

<h1 className='bg-[#6195ff] text-white font-medium'>OUR BLOG</h1>
<h2 className='font-bold text-[20px]'>From Our Blog News</h2>
<div className="flex items-center justify-center text-white text-start w-[100%] flex-wrap" >

<div className="w-[200px] shadow-md shadow-[#6195ff]  bg-[#6195ff] h-[220px]  p-2 m-2  ">
    <div className="mb-[25px]">
    <h1>Rashed kaber</h1>
    <p>22 Aug 2018</p>

    </div>
    <h2 className="mb-[25px]">check at least a doctor in a year for  your teath</h2>
    <Image className='relative left-[10px]' src="/9090.png" alt="image" width={50}height={50} />
    {/* <i><AiOutlineArrowRight/></i> */}
</div>
<div className=" w-[200px] h-[220px] text-black shadow-sm shadow-black p-2 m-2 hover:text-[white] hover:bg-[#6195ff]">
    <div className="flex">
    <Image className='w-[50px] h-[50px] rounded-full' src="/449.jpg" alt="image" width={50}height={50} />
    <div className="">
    <h1 className="font-medium">Dr.cudi</h1>
    <p className='text-sm text-[#000000ab]'>22 Aug 2018</p>
    </div>
    </div>
    <h2 className='font-medium '>2 times of brush in aday con keep you healthy</h2>
<p className='text-[#000000ab] text-[13px] '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus ipsum neque suscipit voluptatibus perspiciatis</p>
</div>

<div className=" w-[200px] h-[220px] text-black shadow-sm shadow-black p-2 m-2 hover:text-[white] hover:bg-[#6195ff]">
    <div className="flex">
<Image className='w-[50px] h-[50px] rounded-full' src="/449.jpg" alt="image" width={50}height={50} />
    <div className="">
    <h1 className="font-medium">Dr.johan</h1>
    <p className='text-sm text-[#000000ab]'>4 Aug 2019</p>
    </div>
    </div>
    <h2 className='font-medium '>2 times of brush in aday con keep you healthy</h2>
<p className='text-[#000000ab] text-[13px] '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus ipsum neque suscipit voluptatibus perspiciatis</p>
</div>
</div>
<div className="mt-10  ">
    <h1 className='text-[#6195ff] font-bold'>Our Doctors</h1>
<div className="flex justify-center mt-4">
<div className="w-[200px] text-center">
<Image className='w-[200px] h-[200px] rounded-full' src="/443.png" alt="image" width={200}height={200} />
        <h1 className='font-bold'>Dr.coudi</h1>
        <div className="flex justify-center items-center text-center">
            {/* <i className='text-[#6195ff]'><AiFillPhone/></i> */}
            <p className=' font-medium text-[13px] text-[#000000ab]'>549 954 123</p>
        </div>
    </div>
    <div className="w-[200px] text-center ">
    <Image className='w-[200px] h-[220px] rounded-full' src="/443.png" alt="image" width={200}height={200} />
        <h1 className='font-bold'>Dr.coudi</h1>
        <div className="flex justify-center items-center text-center">
            {/* <i className='text-[#6195ff]'><AiFillPhone/></i> */}
            <p className=' font-medium text-[13px] text-[#000000ab]'>549 954 123</p>
        </div>
    </div>
    <div className="w-[200px] text-center">
    <Image className='w-[200px] h-[200px] rounded-full' src="/443.png" alt="image" width={200}height={200} />
        <h1 className='font-bold'>Dr.coudi</h1>
        <div className="flex justify-center items-center text-center">
            {/* <i className='text-[#6195ff]'><AiFillPhone/></i> */}
            <p className=' font-medium text-[13px] text-[#000000ab]'>549 954 123</p>
        </div>
    </div>

</div>

</div>
</div>
<Footer/>
</>
);
};

export default Blog;